version: '3.7'

services:
  mongo-db:
    container_name: mega-mall-mongodb
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017

  mongo-express:
    container_name: mega-mall-mongoexpress
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mega-mall-mongodb
    depends_on:
      - mongo-db
    ports:
      - '8081:8081'

  rabbitmq:
    container_name: mega-mall-rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3-management
    environment:
      'RABBITMQ_DEFAULT_PASS': 'J93ra8rYTv8bfzGU'
    ports:
      - '4369:4369'
      - '5672:5672'
      - '15672:15672'
      - '25672:25672'

  mega-mall-api:
    container_name: mega-mall-api
    image: docker.pkg.github.com/andjiev/mega-mall-server/mega-mall-api:1.7
    restart: always
    environment:
      - 'ASPNETCORE_ENVIRONMENT=Development'
      - 'ASPNETCORE_URLS=http://+:6401'
      - 'MegaMallDatabaseSettings__ConnectionString=mongodb://root:root@mongo-db'
      - 'RabbitMQ__Address=rabbitmq'
    depends_on:
      - mongo-db
      - rabbitmq
    ports:
      - 6401:80

  mega-mall-crawler:
    container_name: mega-mall-crawler
    image: docker.pkg.github.com/andjiev/mega-mall-server/mega-mall-crawler:1.7
    restart: always
    environment:
      - 'ASPNETCORE_ENVIRONMENT=Development'
      - 'ASPNETCORE_URLS=http://+:6501'
      - 'MegaMallDatabaseSettings__ConnectionString=mongodb://root:root@mongo-db'
      - 'RabbitMQ__Address=rabbitmq'
    depends_on:
      - mongo-db
      - rabbitmq
    ports:
      - 6501:80
